### ISSUE TITLE
Build scripts incorrectly assume all repos have a 'build.sh'

### ISSUE THREAD

**Issue by abingham** [cyber-dojo/cyber-dojo#1]
In following the build steps described in `dev/README.md`, I ran into a problem where `build-all.sh` was trying to run `build.sh` scripts that didn't exist. Here's what I think is going on:

1. `build-all.sh` is sourcing `env-var-repos.sh`, and this sets the `CYBER_DOJO_REPOS` to a list of repos.
2. For every repo in `CYBER_DOJO_REPOS`, `build-all.sh` cd's to that directory and tries to run `build.sh.`.
3. However, some of those directories (e.g. `starter`) don't contain a `build.sh`, and this causes the script to terminate prematurely.

I see at least two possible approaches to fixing this. First, we could modify `env-var-repos.sh` to only include repos containing `build.sh` in `CYBER_DOJO_REPOS`. Or, we could update `build-all.sh` so that it checks for each potential `build.sh` before running it. 

This second change is very straightforward, and it seems a bit more future-proof insofar as it will automatically pick up new build scripts as they become available.

**Comment by JonJagger** [comment]
Ach yes. This is exactly what happens when you don't have a daily Travis build build to check things.
I think that all repos needs to have a build.sh script.
After all, build-all is supposed to build all of them!

**Comment by JonJagger** [comment]
I've fixed this and added a .travis.yml script to check the git-clone-all.sh and build-all.sh script run to completion without error.
