### ISSUE TITLE
`cyber-dojo up` is looking for the `storer` user which doesn't exist

### ISSUE THREAD

**Issue by abingham** [cyber-dojo/cyber-dojo#2]
The instructions in `dev/README.md` tell me to run `build-all.sh` followed by `cyber-dojo up`. If I do this (after working around #1), the `cyber-dojo up` command fails telling me:
```
ERROR: for cyber-dojo-storer  Cannot start service storer: linux spec user: unable to find user storer: no matching entries in passwd file

ERROR: for storer  Cannot start service storer: linux spec user: unable to find user storer: no matching entries in passwd file
Encountered errors while bringing up the project.
```
It looks like I need to create a user named `storer` somewhere, though I'm not sure if this is on my actual host OS or in a docker container somewhere (if container-specific users are even a thing).

**Comment by JonJagger** [comment]
Yes more problems because there is no Travis.
I will look into it this morning.
I'll get a fix for you as soon as I can.

**Comment by JonJagger** [comment]
What do you get when you run
$ docker run --rm -it cyberdojo/storer sh -c 'id storer'

You should see
uid=19661(storer) gid=19661(storer) groups=19661(storer)

If not try
$ docker pull cyberdojo/storer
and then repeat

**Comment by abingham** [comment]
I see this:
```
 % docker run --rm -it cyberdojo/storer sh -c 'id storer'                                                                                                                                                                                                                                       repos/cyber-dojo goldenhammer
id: unknown user storer
 % docker pull cyberdojo/storer
... docker doing stuff...                                                                                                                                                                                                                                                                 
Status: Downloaded newer image for cyberdojo/storer:latest
 % docker run --rm -it cyberdojo/storer sh -c 'id storer'                                                                                                                                                                                                                                       repos/cyber-dojo goldenhammer
uid=19661(storer) gid=19661(storer) groups=19661(storer)
```

After doing this, `cyber-dojo up` executes without error.

**Comment by JonJagger** [comment]
So it looks like you are up at least :-)
Can you now use your local cyber-dojo in your browser?

**Comment by abingham** [comment]
Not yet. I see grafana served on localhost:3000, but when I go to localhost I get a "502 - Bad Gateway" error. What port/address should be serving cyber-dojo?

**Comment by JonJagger** [comment]
If you're running DockerToolbox for Mac you'll need your default VM's IP
$ docker-machine ip default

**Comment by abingham** [comment]
Ah, right. I used normal docker. Let me retry things with docker machine.

**Comment by JonJagger** [comment]
Hmmm. Do you mean s/machine/toolbox/ ?

**Comment by abingham** [comment]
Sorry, yes, I meant toolbox.

**Comment by abingham** [comment]
OK! Following the instructions but using docker-toolbox seems to work perfectly. I didn't need to pull the storer image either. I'll close this out.

**Comment by JonJagger** [comment]
Super :-)
