### ISSUE TITLE
Output from previous test runs displaying

### ISSUE THREAD

**Issue by dodgees** [cyber-dojo/cyber-dojo#3]
The output of each round of test runs is stacking and continues to be displayed on subsequent iterations. This issue is resolved when the page is refreshed. Identified using Chrome v66.

![image](https://user-images.githubusercontent.com/7633012/39926185-01ccd39e-54f4-11e8-95cf-b31385384d4a.png)

**Comment by JonJagger** [comment]
Hi Erik,
thanks for reporting this. I'm using Chrome v66 and I confirm I can reproduce the error.
But only for Java-Cucumber. If I try, eg, C#-NUnit the output does not stack.
I will look into it.
Thanks again
