### ISSUE TITLE
Cannot generate a new exercise

### ISSUE THREAD

**Issue by mantovanello** [cyber-dojo/cyber-dojo#6]
Hi, guys. 

Not sure if this is the proper space, so I apologize in advance if it's the wrong place.

That said, our team uses the Cyber Dojo during our interview process so we can know a bit more about how the developer builds the solution and even know him as a person, because we believe that the code can tell us a lot. But, sadly, today we experienced a problem during the exercise gerenation that made it impossible to create a new one.

Looks like the button below isn't working properly:
![image](https://user-images.githubusercontent.com/3758244/104241319-3d691580-543c-11eb-9ce5-21db849041b9.png)

Could you take a look at it?

Thanks a lot.

**Comment by JonJagger** [comment]
Hi Felipe,
thanks for reporting this. Sorry for the error which has now been fixed.
Cheers
Jon

**Comment by mantovanello** [comment]
Thanks again, Jon!
I appreciate the quick response.

**Comment by JonJagger** [comment]
Hi Felipe,
About the interviews you mentioned...
Do you work for a commercial organization?
If so, can I gently check if the organization has bought a license?
You can choose how much or how little to pay for it!
Cheers
Jon

**Comment by mantovanello** [comment]
Hey, Jon.

Actually, yes, we are a team of 2 devs from a small startup from Brazil. We are using Cyber Dojo during the process to add another dev to our team.

TBH, we didn't notice there was a license for commercial use, I apologize. Anyway, we are interested in donate and get a license. Yet, we only used Cyber Dojo a few times til now and after we close the job opportunity, it will take some time to use it again.

Could you explain about the options we have regarding the license itself?

Thanks,
Felipe

**Comment by JonJagger** [comment]
Hi Felipe.
No worries. The license info is on the home page. Just scroll down a little.
You can buy your license with a donation. Just make sure to write your company name when filling in the PayPal form.
The longer way, is you tell me how much you'd like to pay for your license, I create an invoice and send it to you. You can pay that via the bank details on the invoice, or you can still use the donate button.
Cheers
Jon
