### ISSUE TITLE
Text file is lost after running a test with a stray '\20' in the file

### ISSUE THREAD

**Issue by claremacrae** [cyber-dojo/cyber-dojo#7]
## Summary

Something about my keyboard setup means that if I hit a particular key, then a non-ascii character gets inserted.

If I run the tests without spotting it, here's what happens:

Expected behaviour: error message saying my code is wrong
Actual  behaviour: error message saying my code is wrong - and the source file is removed from the list of available files.

It's a windows keyboard attached to a Mac, and the key that on PCs causes the context menu to appear, in cyber-dojo causes a little round circle to appear in the code.

## Workaround

This has happened to me 3 times now, in an online course, and each time I have had to use the '+' sign to create a new file, and copy-and-paste the in the file from a previous step, which took a few minutes.

I see now that I can "revert" an earlier step, but either I didn't spot that, at the time - or I tried it, and it didn't seem to re-add the file... 

## Steps to reproduce

Here's exactly what I did - I suspect some of the middle steps can be removed...

1. Start a new session - I chose C++ with CppUTest and Roman numerals
2. Run the test and confirm they fail
3. Edit HikerTest.cpp to make the failing test pass
4. Accidentally hit a key on my keyboard that puts a '\20' (little round blob) into the source
5. Run the tests

## Example

There is an example of this having happened in Step 3 of https://www.cyber-dojo.org/kata/edit/8HV74p

This is the error text in the output window:

```
:stdout:
compiling AllTests.cpp
compiling HikerTest.cpp

:stderr:
tests/HikerTest.cpp:22:5: error: stray '\20' in program
   22 |     
      |     ^
make: *** [/cpputest/build/MakefileWorker.mk:511: objs/tests/HikerTest.o] Error 1

:status:
2
```

And here is a screenshot: notice how the output file refers to `HikerTest.cpp` but that file is no longer listed in the list of available files:

![image](https://user-images.githubusercontent.com/4840096/104580827-a9729600-5655-11eb-9b12-e0bd9b00becb.png)

**Comment by JonJagger** [comment]
Fantastic bug! Thank you so much for reporting it.
Can I ask you to do the following please...
After inserting the rogue character, but before hitting [test], could you edit cyber-dojo.sh so  line 22 (the call to make) reads

ls -al
make
ls -al

This would be a good first step in determining when the file goes into a black hole!
Thanks

**Comment by JonJagger** [comment]
It would also be very useful if you could deliberately insert the rogue character for a different language, say Ruby+MiniTest, and see if the same file deletion occurs.  Thanks again.

**Comment by claremacrae** [comment]
> Can I ask you to do the following please...
> After inserting the rogue character, but before hitting [test], could you edit cyber-dojo.sh so line 22 (the call to make) reads
> 
> ls -al
> make
> ls -al
> 
> This would be a good first step in determining when the file goes into a black hole!
> Thanks

https://www.cyber-dojo.org/kata/edit/8HV74p

* Run 6 shows a passing build, with the added lines in the script
* Run 7 shows a failing build after adding the stray character...

I guess make it a recursive `ls -alR`

* Run 10 - passing build with listing
* Run 11 - failing build - I put the character in AllTests.cpp by mistake... it disappeared from the file list in the UI, but is still present on disk - suggesting it's a UI issue only....

Screenshot of Run 11:

![Uploading image.png…]()

**Comment by claremacrae** [comment]
Console output from Run 11

```
:stdout:
.:
total 24
drwxrwxrwt 4 sandbox sandbox  180 Jan 14 12:31 .
drwxr-xr-x 1 root    root    4096 Jan 14 12:31 ..
-rw-r--r-- 1 sandbox sandbox  110 Jan 13 18:11 Hiker.cpp
-rw-r--r-- 1 sandbox sandbox  214 Jan 13 18:11 Hiker.hpp
-rw-r--r-- 1 sandbox sandbox  644 Jan 13 18:11 cyber-dojo.sh
-rw-r--r-- 1 sandbox sandbox  400 Jan 13 18:11 makefile
-rw-r--r-- 1 sandbox sandbox  915 Jan 13 18:11 readme.txt
drwxr-xr-x 2 sandbox sandbox   40 Jan 14 12:31 report
drwxr-xr-x 2 sandbox sandbox   80 Jan 14 12:31 tests

./report:
total 0
drwxr-xr-x 2 sandbox sandbox  40 Jan 14 12:31 .
drwxrwxrwt 4 sandbox sandbox 180 Jan 14 12:31 ..

./tests:
total 8
drwxr-xr-x 2 sandbox sandbox  80 Jan 14 12:31 .
drwxrwxrwt 4 sandbox sandbox 180 Jan 14 12:31 ..
-rw-r--r-- 1 sandbox sandbox 112 Jan 13 18:11 AllTests.cpp
-rw-r--r-- 1 sandbox sandbox 452 Jan 13 18:11 HikerTest.cpp
compiling AllTests.cpp
.:
total 24
drwxrwxrwt 5 sandbox sandbox  200 Jan 14 12:31 .
drwxr-xr-x 1 root    root    4096 Jan 14 12:31 ..
-rw-r--r-- 1 sandbox sandbox  110 Jan 13 18:11 Hiker.cpp
-rw-r--r-- 1 sandbox sandbox  214 Jan 13 18:11 Hiker.hpp
-rw-r--r-- 1 sandbox sandbox  644 Jan 13 18:11 cyber-dojo.sh
-rw-r--r-- 1 sandbox sandbox  400 Jan 13 18:11 makefile
drwxr-xr-x 3 sandbox sandbox   60 Jan 14 12:31 objs
-rw-r--r-- 1 sandbox sandbox  915 Jan 13 18:11 readme.txt
drwxr-xr-x 2 sandbox sandbox   40 Jan 14 12:31 report
drwxr-xr-x 2 sandbox sandbox   80 Jan 14 12:31 tests

./objs:
total 0
drwxr-xr-x 3 sandbox sandbox  60 Jan 14 12:31 .
drwxrwxrwt 5 sandbox sandbox 200 Jan 14 12:31 ..
drwxr-xr-x 2 sandbox sandbox  60 Jan 14 12:31 tests

./objs/tests:
total 4
drwxr-xr-x 2 sandbox sandbox   60 Jan 14 12:31 .
drwxr-xr-x 3 sandbox sandbox   60 Jan 14 12:31 ..
-rw-r--r-- 1 sandbox sandbox 1794 Jan 14 12:31 AllTests.d

./report:
total 0
drwxr-xr-x 2 sandbox sandbox  40 Jan 14 12:31 .
drwxrwxrwt 5 sandbox sandbox 200 Jan 14 12:31 ..

./tests:
total 8
drwxr-xr-x 2 sandbox sandbox  80 Jan 14 12:31 .
drwxrwxrwt 5 sandbox sandbox 200 Jan 14 12:31 ..
-rw-r--r-- 1 sandbox sandbox 112 Jan 13 18:11 AllTests.cpp
-rw-r--r-- 1 sandbox sandbox 452 Jan 13 18:11 HikerTest.cpp

:stderr:
tests/AllTests.cpp:7:1: error: stray '\20' in program
    7 | 
      | ^
make: *** [/cpputest/build/MakefileWorker.mk:511: objs/tests/AllTests.o] Error 1

:status:
0
```

**Comment by claremacrae** [comment]
> It would also be very useful if you could deliberately insert the rogue character for a different language, say Ruby+MiniTest, and see if the same file deletion occurs. Thanks again.

Ooohh - good call....

https://www.cyber-dojo.org/kata/edit/Swrw9N

* Run 3 - passing build, with file listing
* Run 4 - failing build with stray character - and `test_hiker.rb` disappeared from the file listing...

Screenshot of Run 4

![image](https://user-images.githubusercontent.com/4840096/104592070-8cde5a00-5665-11eb-924f-076b2ed70cf0.png)

**Comment by claremacrae** [comment]
https://www.cyber-dojo.org/kata/edit/8HV74p

* Run 14... I though I would be clever and add the stray character to the `readme.txt`, so you could copy-and-paste it in to source code and experiment... Unfortunately, this caused the `readme.txt` to disappear from the UI as well!

**Comment by JonJagger** [comment]
Excellent. Big thanks for those.
It's interesting because I do explicitly clean the files, looking for this kind of thing.
I will create a failing test case and look into it. Will be tomorrow.

**Comment by JonJagger** [comment]
Another request if I may... Immediately after hitting [test] and causing a file to be deleted, could you open the browser console and see if anything is reported.
Thanks

**Comment by claremacrae** [comment]
> Another request if I may... Immediately after hitting [test] and causing a file to be deleted, could you open the browser console and see if anything is reported.
> Thanks

Is this what you mean... From run 16 in https://www.cyber-dojo.org/kata/edit/8HV74p

![image](https://user-images.githubusercontent.com/4840096/104710504-13537400-5718-11eb-90a7-8775a4e25452.png)

**Comment by JonJagger** [comment]
That's something different!
I had a good look at the code last night.
I think I have a good idea why it is happening.
Pretty busy today.
First step will be to find out how to insert a rogue character into test input data in Ruby.
Will write a failing test for that over the weekend :-)

**Comment by JonJagger** [comment]
Hi Clare,
There is no output from the second [ls -alR] command because the make is failing (I think)
Could you try replacing line 22 (the call to make) with

ls -alR
make || true
ls -alR

And post the console output here again please.
Thanks

**Comment by JonJagger** [comment]
Hi again!
Making a bit of progress here... this is a fun bug!
I think the problem may involve the file with the rogue character being seen as a binary file (inside the container)...
Could you try replacing line 22 with this... where FILENAME is replaced with the name of the file in which you have inserted the rogue character...

ls -alR
file --mime-encoding FILENAME
make || true
ls -alR

**Comment by claremacrae** [comment]
Thanks - that makes sense.

I'm clutching at straws here, as I don't know the implementation... But just in case it triggers any ideas...

1. Is there any UI state stored?

If so, could a file be retained if it was previously in the file list, unless it actually was deleted from disk?

Although I realise that this might be problematical if the user reverted back to earlier revisions - you'd have to keep a list of all files in all versions...

2. Maybe include a hidden file that contains the current list of files displayed?

3. Does `file --raw` help?

```
  -r, --raw                  don't translate unprintable chars to \ooo
```

**Comment by claremacrae** [comment]
4. You've got the list of files known to git in any given revision... Maybe always all files known to git in the list?

It's not perfect, but it would be an improvement...

**Comment by JonJagger** [comment]
Ok. I've got something which I'm hoping will solve the problem.
Only deployed on beta for now.
Could you try on https://beta.cyber-dojo.org please.
Thanks

**Comment by claremacrae** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉 

It's fixed - I tried breaking it several ways in https://beta.cyber-dojo.org/kata/edit/uRjRLJ

Huge thanks!!!

**Comment by JonJagger** [comment]
Excellent. Now live on the main site.
Thanks again.
